[package]
name = "rask"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
description = "Low-level HTTP for learning purposes"
homepage = "https://github.com/ryanseipp/rask"
repository = "https://github.com/ryanseipp/rask"
readme = "README.md"

[dependencies]
mio = { version = "0.8", features = ["os-poll", "net"] }
slab = "0.4"

[[example]]
name = "example"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = false

[profile.dev]
debug = true
opt-level = 0
