[package]
name = "rask"
description = "HTTP/1.1, HTTP/2 and HTTP/3 server"

version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
mio.workspace = true
slab.workspace = true
parser.path = "../parser"
