env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          override: true
          profile: minimal
          toolchain: ${{ matrix.version }}

      - uses: actions-rs/cargo@v1
        with:
          command: build

      - uses: actions-rs/cargo@v1
        with:
          command: test

      - uses: actions-rs/cargo@v1
        with:
          args: --all -- --check
          command: fmt

      - uses: actions-rs/cargo@v1
        with:
          args: -- -D warnings
          command: clippy

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        version: ["nightly"]

name: CI
on: [push, pull_request]
